services:
  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  ###< symfony/mailer ###

  ###> symfony/mercure-bundle ###
  mercure:
    ports:
      - "9090:80"
  ###< symfony/mercure-bundle ###

  ###> adminer ###
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      # THEMES: 'pepa-linha-dark', 'hydra', 'lucas-sandery', 'mvt'
      # See list: https://www.adminer.org/en/designs/
      ADMINER_DESIGN: pepa-linha-dark
      # Default to Postgres so you don't have to select it every time
      ADMINER_DEFAULT_SERVER: postgres
  ###< adminer ###
