lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
#    token_ttl: 3600 # 1 hour
    token_ttl: 1200 # 20 minutes
#    token_ttl: 30 # 1 minute
    user_id_claim: email
